# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a501c16b8f9f007fbc92e1ea4e14686a4720be125d576d20452040b812986d812d5fcc99b4167e29e66cf5d725351eacb711f084d2f94b9be8b5fada03748f1d

test:
  secret_key_base: 44e4217cdf32dcb82cd6e2de3ece8661c85e6f3338770519ab09acbf9736ec7f0fd9a47830ae01bcfaf427453ccbaf6e57eadc0e45ff47cb0f0595af1b6b3621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
